### ISSUE TITLE
Add reencryption support

### ISSUE THREAD

**Issue by norling** [neicnordic/sda-download#241] opened 2023-03-01 09:11 UTC
As a user 
I want to be able to download files reencrypted with my public crypt4gh key.

A/C:
 - [ ] A way of identifying if files are requested as decrypted or reencrypted
 - [ ] Reading public keys from a secondary system (likely the database)
 - [ ] Serving reencrypted files for download

See also neicnordic/sda-download#4

This can be done by using a new service that we are developing for re-encrypting headers.

**Comment by blankdots** [comment] 2023-03-01 09:37
duplicate of #60

**Closed** 2023-12-06 08:57 UTC
